Publish crate if not published with version check

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -44,16 +44,17 @@ jobs:
           echo "searching for ${{ matrix.crate }} = \"${{ steps.read-version.outputs.version }}\"
           cargo search ${{ matrix.crate }} --limit 1 | grep -q "${{ matrix.crate }} = \"${{ steps.read-version.outputs.version }}\""
           echo $?
-          set +x
 
-          echo "if ${{ matrix.crate }} = \"${{ steps.read-version.outputs.version }}\"
-          if cargo search ${{ matrix.crate }} --limit 1 | grep -q "${{ matrix.crate }} = \"${{ steps.read-version.outputs.version }}\""; then
-            echo "published=yes"
+          cargo search ${{ matrix.crate }} --limit 1 | grep -q "${{ matrix.crate }} = \"${{ steps.read-version.outputs.version }}\""
+          if [ $? -eq 0 ]; then
+            echo "The package ${matrix.crate} with version ${steps.read-version.outputs.version} is found. Setting published=yes."
             echo "published=yes" >> $GITHUB_OUTPUT
           else
-            echo "published=no"
+            echo "The package ${matrix.crate} with version ${steps.read-version.outputs.version} is not found. Setting published=no."
             echo "published=no" >> $GITHUB_OUTPUT
           fi
+
+          set +x
 
       - name: Publish crate if not published
         if: ${{ steps.check-published.outputs.published }} == 'no'
